### ISSUE TITLE
why has the on stage mod been pulled?

### ISSUE THREAD

**Issue by crisisasam** [guanaco0403/Guanaco-Firework-Mania-Mods#10]
on stage
In which of my mod do you have this question ?

why is the on stage mod no longer on mod.io or your GitHub page?
A clear and concise description of your question.

many of my saves have this mod in it and it is sad to see it go. 
if you have something else to say

this hasn't happened before today and i can not see it listed anywhere anymore.

**Comment by guanaco0403** [comment]
Hello @crisisasam , the mod is temporaly set hidden its not been deleted.
I need to fix some things on it and remove the screens because a lot of peoples are asking me why it doesnt work anymore.
Youtube changed its API and its no more possible to retrieve a video with its url.
But once il have changed that il re-enable the mod.

**Comment by guanaco0403** [comment]
Mhh I will re-enable it now because if your savs are using it its important
